/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppVitalsRouteImport } from './routes/_authenticated.app.vitals'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated.app.settings'
import { Route as AuthenticatedAppMedicationsRouteImport } from './routes/_authenticated.app.medications'
import { Route as AuthenticatedAppInsightsRouteImport } from './routes/_authenticated.app.insights'
import { Route as AuthenticatedAppCareTeamRouteImport } from './routes/_authenticated.app.care-team'
import { Route as AuthenticatedAppAlertsRouteImport } from './routes/_authenticated.app.alerts'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppVitalsRoute = AuthenticatedAppVitalsRouteImport.update({
  id: '/app/vitals',
  path: '/app/vitals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/app/settings',
    path: '/app/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppMedicationsRoute =
  AuthenticatedAppMedicationsRouteImport.update({
    id: '/app/medications',
    path: '/app/medications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppInsightsRoute =
  AuthenticatedAppInsightsRouteImport.update({
    id: '/app/insights',
    path: '/app/insights',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppCareTeamRoute =
  AuthenticatedAppCareTeamRouteImport.update({
    id: '/app/care-team',
    path: '/app/care-team',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppAlertsRoute = AuthenticatedAppAlertsRouteImport.update({
  id: '/app/alerts',
  path: '/app/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/care-team': typeof AuthenticatedAppCareTeamRoute
  '/app/insights': typeof AuthenticatedAppInsightsRoute
  '/app/medications': typeof AuthenticatedAppMedicationsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/vitals': typeof AuthenticatedAppVitalsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/app/care-team': typeof AuthenticatedAppCareTeamRoute
  '/app/insights': typeof AuthenticatedAppInsightsRoute
  '/app/medications': typeof AuthenticatedAppMedicationsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/vitals': typeof AuthenticatedAppVitalsRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app/alerts': typeof AuthenticatedAppAlertsRoute
  '/_authenticated/app/care-team': typeof AuthenticatedAppCareTeamRoute
  '/_authenticated/app/insights': typeof AuthenticatedAppInsightsRoute
  '/_authenticated/app/medications': typeof AuthenticatedAppMedicationsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/vitals': typeof AuthenticatedAppVitalsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/app/alerts'
    | '/app/care-team'
    | '/app/insights'
    | '/app/medications'
    | '/app/settings'
    | '/app/vitals'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/app/alerts'
    | '/app/care-team'
    | '/app/insights'
    | '/app/medications'
    | '/app/settings'
    | '/app/vitals'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/app/alerts'
    | '/_authenticated/app/care-team'
    | '/_authenticated/app/insights'
    | '/_authenticated/app/medications'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/vitals'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/vitals': {
      id: '/_authenticated/app/vitals'
      path: '/app/vitals'
      fullPath: '/app/vitals'
      preLoaderRoute: typeof AuthenticatedAppVitalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/medications': {
      id: '/_authenticated/app/medications'
      path: '/app/medications'
      fullPath: '/app/medications'
      preLoaderRoute: typeof AuthenticatedAppMedicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/insights': {
      id: '/_authenticated/app/insights'
      path: '/app/insights'
      fullPath: '/app/insights'
      preLoaderRoute: typeof AuthenticatedAppInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/care-team': {
      id: '/_authenticated/app/care-team'
      path: '/app/care-team'
      fullPath: '/app/care-team'
      preLoaderRoute: typeof AuthenticatedAppCareTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/alerts': {
      id: '/_authenticated/app/alerts'
      path: '/app/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AuthenticatedAppAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppAlertsRoute: typeof AuthenticatedAppAlertsRoute
  AuthenticatedAppCareTeamRoute: typeof AuthenticatedAppCareTeamRoute
  AuthenticatedAppInsightsRoute: typeof AuthenticatedAppInsightsRoute
  AuthenticatedAppMedicationsRoute: typeof AuthenticatedAppMedicationsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppVitalsRoute: typeof AuthenticatedAppVitalsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppAlertsRoute: AuthenticatedAppAlertsRoute,
  AuthenticatedAppCareTeamRoute: AuthenticatedAppCareTeamRoute,
  AuthenticatedAppInsightsRoute: AuthenticatedAppInsightsRoute,
  AuthenticatedAppMedicationsRoute: AuthenticatedAppMedicationsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppVitalsRoute: AuthenticatedAppVitalsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
